### ISSUE TITLE
Unhandled rejection Error: Cypher and Batch not available

### ISSUE THREAD

**Issue by ekkis** [objectundefined/node-cypher#2]
I grabbed the latest from npm, followed the README example and generated this error:

> TypeError: Cannot read property 'cypher' of undefined
>     at Request._callback (/.../node_modules/node-cypher/index.js:23:20)

the problem which owes to this line in the `index.js`:

```
 23     } else if (json.cypher && json.batch) {
```

...which I fixed like this:

```
 23     } else if (json && json.cypher && json.batch) {
```

I'm not sure why `json` wouldn't be defined but the code is more robust if it makes sure the variable is not null before dereferencing.  with that fix I now see another error:

```
Unhandled rejection Error: Cypher and Batch not available
    at Request._callback (/.../node_modules/node-cypher/index.js:30:17)
```

this error stems from the fact that the callback is defined to receive `(err,result,json)` and we seem to want the last argument, but it's null.  in fact, `result` has a value.  so I thought at first it could be because my cypher didn't return anything e.g. `create (:test)` so I made it return something `create (n:test) return n` but `json` is still empty.  what could be the issue here?

**Comment by ekkis** [comment]
figured it out.  the problem is I was passing in a url terminated in a slash, which caused for an inexistent path e.g. `http://neo4j:somepass@localhost:7474//db/data`.  the answer is to change the line below:

`8   var httpOpts = self._httpOpts = _.isString(hostOrConnOpts) ? { host : hostOrConnOpts } : hostOrConnOpts || {} ;
`
to something like:
`8   var httpOpts = self._httpOpts = _.isString(hostOrConnOpts) ? { host : host    OrConnOpts.replace(/\/$/, '') } : hostOrConnOpts || {} ;
`
